In [1]:
%pip install numpy
import numpy as np

#each row is gradient loss from each input
dvalues=np.array([[1,1,1],
                 [2,2,2],
                 [3,3,3] 
            ])

inputs=np.array([
    [1,2,3,2.5],
    [2,5,-1,2],
    [-1.5,2.7,3.3,-0.8]
])
#each row is a weight from each neuron

dweights=np.dot(inputs.T,dvalues)
print(dweights)

Note: you may need to restart the kernel to use updated packages.
[[ 0.5  0.5  0.5]
 [20.1 20.1 20.1]
 [10.9 10.9 10.9]
 [ 4.1  4.1  4.1]]


In [2]:
dvalues=np.array([[1,1,1],
                 [2,2,2],
                 [3,3,3] 
            ])

biases=np.array([[2,3,0.5]])

dbiases=np.sum(dvalues,axis=0,keepdims=True)
print(dbiases)

[[6 6 6]]


In [ ]:
import numpy as np
# Passed-in gradient from the next layer
# for the purpose of this example we're going to use
# an array of an incremental gradient values
dvalues = np.array([[1., 1., 1.],
 [2., 2., 2.],
 [3., 3., 3.]])
# We have 3 sets of weights - one set for each neuron
# we have 4 inputs, thus 4 weights
# recall that we keep weights transposed
weights = np.array([[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]).T
# sum weights of given input
# and multiply by the passed-in gradient for this neuron
dinputs = np.dot(dvalues, weights.T)
print(dinputs)

In [ ]:
# class Layer_Dense:


#     def backward(self,dvalues):
#         self.dweights=np.dot(self.inputs.T,dvalues)
#         self.biases=np.sum(dvalues,axis=0,keepdims=True)
#         self.dinputs=np.dot(dvalues,self.weight.T)

In [ ]:
# class Activation_ReLU:

#     def forward(self,inputs):
#         self.output=np.maximum(0,inputs)


#     def backward(self,dvalues):
#         self.dinputs=dvalues.copy()
#         self.dinputs[self.inputs<=0]=0